### ISSUE TITLE
Module not found - line-awesome

### ISSUE THREAD

**Issue by devcocup** [flatlogic/sing-app#23]
I purchased the sing-app-react pro version and I am trying to run this awesome template on my local machine.  
But I am getting error - `Module not found ... ` during npm start after yarn install.  
![Screen Shot 2020-07-08 at 12 13 50 AM](https://user-images.githubusercontent.com/39966311/86849468-ffb3ba80-c0af-11ea-94f8-21a0fac057ad.png)

I've checked the line-awesome package under node_modules and there is no such css file.
I've repeated install/uninstall node_modules, but no luck so far. It seems line-awesome module was installed correctly first time.  

Please help me how we can solve this problem.

**Comment by Blari** [comment]
Hi!
Fixed )
