### ISSUE TITLE
Download or Clone Project???

### ISSUE THREAD

**Issue by TioWidow** [flatlogic/sing-app#3]
I'm looking for the sing-app examples to download and I have not found a way to do it.

The "Download" button in the README.MD file also leads to a page not found.

I Receive the email:
"You requested an access to our GitHub repository. Here is the link https://github.com/flatlogic/sing" but page not found
Where can I download it?

**Comment by keksonov** [comment]
Please, send your license code to  contact@flatlogic.com with link to this issue.
